[package]
name = "rusty-butler"
version = "0.1.0"
authors = ["Ward Muylaert <ward.muylaert@gmail.com>"]

[lib]
name = "rusty_butler_lib"
path = "src/lib.rs"

[[bin]]
name = "rusty-butler-bin"
path = "src/main.rs"

[dependencies]
irc = "0.13.5"
chrono = "0.4.3"
regex = "1.0.1"
reqwest = "0.8.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rink = "0.4"
unicode-segmentation = "1.2.0"
